repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: local
    hooks:
      - id: jupytext-clean-python
        name: jupytext-clean-python
        entry: ./.pre-commit-scripts/clean_md.sh python
        files: ^measured_analysis_figures/.*\.md$
        language: python
        additional_dependencies:
          - jupytext==1.16.1
  - repo: local
    hooks:
      - id: jupytext-clean-julia
        name: jupytext-clean-julia
        entry: ./.pre-commit-scripts/clean_md.sh julia
        files: ^ParityReadoutSimulator/.*\.md$
        language: python
        additional_dependencies:
          - jupytext==1.16.1
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.26
    hooks:
      - id: uv-lock
      - id: uv-export
